# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/phraseanet-idx
pkgincludedir = $(includedir)/phraseanet-idx
pkglibdir = $(libdir)/phraseanet-idx
pkglibexecdir = $(libexecdir)/phraseanet-idx
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-apple-darwin12.5.0
host_triplet = x86_64-apple-darwin12.5.0
bin_PROGRAMS = phraseanet_indexer$(EXEEXT)
subdir = .
DIST_COMMON = $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure \
	config/config.guess config/config.sub config/depcomp \
	config/install-sh config/ltmain.sh config/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_phraseanet_indexer_OBJECTS = src/phraseanet_indexer-main.$(OBJEXT) \
	src/phraseanet_indexer-callback_record.$(OBJEXT) \
	src/phraseanet_indexer-connbas.$(OBJEXT) \
	src/phraseanet_indexer-connbas_abox.$(OBJEXT) \
	src/phraseanet_indexer-connbas_dbox.$(OBJEXT) \
	src/phraseanet_indexer-dom.$(OBJEXT) \
	src/phraseanet_indexer-indexer.$(OBJEXT) \
	src/phraseanet_indexer-unicode.$(OBJEXT) \
	src/phraseanet_indexer-phrasea_clock_t.$(OBJEXT) \
	src/phraseanet_indexer-sbas.$(OBJEXT) \
	src/phraseanet_indexer-thesaurus.$(OBJEXT) \
	src/phraseanet_indexer-trace_memory.$(OBJEXT) \
	src/phraseanet_indexer-sockets.$(OBJEXT) \
	xNIX/phraseanet_indexer-syslog_xnix.$(OBJEXT)
phraseanet_indexer_OBJECTS = $(am_phraseanet_indexer_OBJECTS)
phraseanet_indexer_DEPENDENCIES = libstemmer_c/libstemmer.a
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(phraseanet_indexer_SOURCES)
DIST_SOURCES = $(phraseanet_indexer_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-dvi-recursive install-exec-recursive \
	install-html-recursive install-info-recursive \
	install-pdf-recursive install-ps-recursive install-recursive \
	installcheck-recursive installdirs-recursive pdf-recursive \
	ps-recursive uninstall-recursive
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
AM_RECURSIVE_TARGETS = $(RECURSIVE_TARGETS:-recursive=) \
	$(RECURSIVE_CLEAN_TARGETS:-recursive=) tags TAGS ctags CTAGS \
	distdir dist dist-all distcheck
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/macjy/workspace/Phraseanet-Indexer/config/missing --run aclocal-1.11
AMTAR = ${SHELL} /Users/macjy/workspace/Phraseanet-Indexer/config/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /Users/macjy/workspace/Phraseanet-Indexer/config/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/macjy/workspace/Phraseanet-Indexer/config/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/macjy/workspace/Phraseanet-Indexer/config/missing --run automake-1.11
AWK = awk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS =  -I/usr/include/libxml2 -I/usr/local/mysql-5.6.14-osx10.7-x86_64/include  -Os -g -fno-strict-aliasing -arch x86_64
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"Phraseanet-Idx\" -DPACKAGE_TARNAME=\"phraseanet-idx\" -DPACKAGE_VERSION=\"3.10.2.1\" -DPACKAGE_STRING=\"Phraseanet-Idx\ 3.10.2.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBMYSQLCLIENT=1 -DHAVE_LIBXML2=1 -DHAVE_LIBEXPAT=1 -DHAVE_LIBPTHREAD=1 -DHAVE_EXPAT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_LIMITS_H=1 -DHAVE_LOCALE_H=1 -DHAVE_MEMORY_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYS_TIMEB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_WCHAR_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_MEMSET=1 -DHAVE_SELECT=1 -DHAVE_SETLOCALE=1 -DHAVE_SOCKET=1 -DHAVE_STRCASECMP=1 -DHAVE_STRCHR=1 -DHAVE_STRRCHR=1
DEPDIR = .deps
DSYMUTIL = dsymutil
DUMPBIN = 
ECHO_C = \c
ECHO_N = 
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = -lpthread -lexpat -lxml2 -lmysqlclient 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = lipo
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/macjy/workspace/Phraseanet-Indexer/config/missing --run makeinfo
MKDIR_P = config/install-sh -c -d
MYSQL_CONFIG = /usr/local/bin/mysql_config
NM = /usr/bin/nm
NMEDIT = nmedit
OBJDUMP = false
OBJEXT = o
OSXMYSQLLIBDIR = 
OTOOL = otool
OTOOL64 = :
PACKAGE = phraseanet-idx
PACKAGE_BUGREPORT = 
PACKAGE_NAME = Phraseanet-Idx
PACKAGE_STRING = Phraseanet-Idx 3.10.2.1
PACKAGE_TARNAME = phraseanet-idx
PACKAGE_URL = 
PACKAGE_VERSION = 3.10.2.1
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 3.10.2.1
abs_builddir = /Users/macjy/workspace/Phraseanet-Indexer
abs_srcdir = /Users/macjy/workspace/Phraseanet-Indexer
abs_top_builddir = /Users/macjy/workspace/Phraseanet-Indexer
abs_top_srcdir = /Users/macjy/workspace/Phraseanet-Indexer
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = x86_64-apple-darwin12.5.0
build_alias = 
build_cpu = x86_64
build_os = darwin12.5.0
build_vendor = apple
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-apple-darwin12.5.0
host_alias = 
host_cpu = x86_64
host_os = darwin12.5.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /Users/macjy/workspace/Phraseanet-Indexer/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = /bin/echo
mandir = ${datarootdir}/man
mkdir_p = $(top_builddir)/config/install-sh -c -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
EXTRA_DIST = autogen.sh
AUTOMAKE_OPTIONS = subdir-objects
AM_CPPFLAGS = -I$(top_srcdir)/libstemmer_c/include
SUBDIRS = libstemmer_c src
phraseanet_indexer_SOURCES = \
    src/main.cpp \
    src/_version.h \
    src/callback_record.cpp \
    src/connbas.cpp \
    src/connbas_abox.cpp \
    src/connbas_dbox.cpp \
    src/dom.cpp \
    src/indexer.cpp \
    src/unicode.cpp \
    src/phrasea_clock_t.cpp \
    src/sbas.cpp \
    src/thesaurus.cpp \
    src/trace_memory.cpp \
    src/sockets.cpp \
    xNIX/syslog_xnix.cpp

phraseanet_indexer_CPPFLAGS = -I$(top_srcdir)/libstemmer_c/include
phraseanet_indexer_LDADD = libstemmer_c/libstemmer.a
all: all-recursive

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-main.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-callback_record.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-connbas.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-connbas_abox.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-connbas_dbox.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-dom.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-indexer.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-unicode.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-phrasea_clock_t.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-sbas.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-thesaurus.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-trace_memory.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/phraseanet_indexer-sockets.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
xNIX/$(am__dirstamp):
	@$(MKDIR_P) xNIX
	@: > xNIX/$(am__dirstamp)
xNIX/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) xNIX/$(DEPDIR)
	@: > xNIX/$(DEPDIR)/$(am__dirstamp)
xNIX/phraseanet_indexer-syslog_xnix.$(OBJEXT): xNIX/$(am__dirstamp) \
	xNIX/$(DEPDIR)/$(am__dirstamp)
phraseanet_indexer$(EXEEXT): $(phraseanet_indexer_OBJECTS) $(phraseanet_indexer_DEPENDENCIES) 
	@rm -f phraseanet_indexer$(EXEEXT)
	$(CXXLINK) $(phraseanet_indexer_OBJECTS) $(phraseanet_indexer_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/phraseanet_indexer-callback_record.$(OBJEXT)
	-rm -f src/phraseanet_indexer-connbas.$(OBJEXT)
	-rm -f src/phraseanet_indexer-connbas_abox.$(OBJEXT)
	-rm -f src/phraseanet_indexer-connbas_dbox.$(OBJEXT)
	-rm -f src/phraseanet_indexer-dom.$(OBJEXT)
	-rm -f src/phraseanet_indexer-indexer.$(OBJEXT)
	-rm -f src/phraseanet_indexer-main.$(OBJEXT)
	-rm -f src/phraseanet_indexer-phrasea_clock_t.$(OBJEXT)
	-rm -f src/phraseanet_indexer-sbas.$(OBJEXT)
	-rm -f src/phraseanet_indexer-sockets.$(OBJEXT)
	-rm -f src/phraseanet_indexer-thesaurus.$(OBJEXT)
	-rm -f src/phraseanet_indexer-trace_memory.$(OBJEXT)
	-rm -f src/phraseanet_indexer-unicode.$(OBJEXT)
	-rm -f xNIX/phraseanet_indexer-syslog_xnix.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/phraseanet_indexer-callback_record.Po
include src/$(DEPDIR)/phraseanet_indexer-connbas.Po
include src/$(DEPDIR)/phraseanet_indexer-connbas_abox.Po
include src/$(DEPDIR)/phraseanet_indexer-connbas_dbox.Po
include src/$(DEPDIR)/phraseanet_indexer-dom.Po
include src/$(DEPDIR)/phraseanet_indexer-indexer.Po
include src/$(DEPDIR)/phraseanet_indexer-main.Po
include src/$(DEPDIR)/phraseanet_indexer-phrasea_clock_t.Po
include src/$(DEPDIR)/phraseanet_indexer-sbas.Po
include src/$(DEPDIR)/phraseanet_indexer-sockets.Po
include src/$(DEPDIR)/phraseanet_indexer-thesaurus.Po
include src/$(DEPDIR)/phraseanet_indexer-trace_memory.Po
include src/$(DEPDIR)/phraseanet_indexer-unicode.Po
include xNIX/$(DEPDIR)/phraseanet_indexer-syslog_xnix.Po

.cpp.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

src/phraseanet_indexer-main.o: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-main.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-main.Tpo -c -o src/phraseanet_indexer-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-main.Tpo src/$(DEPDIR)/phraseanet_indexer-main.Po
#	source='src/main.cpp' object='src/phraseanet_indexer-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp

src/phraseanet_indexer-main.obj: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-main.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-main.Tpo -c -o src/phraseanet_indexer-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-main.Tpo src/$(DEPDIR)/phraseanet_indexer-main.Po
#	source='src/main.cpp' object='src/phraseanet_indexer-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`

src/phraseanet_indexer-callback_record.o: src/callback_record.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-callback_record.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-callback_record.Tpo -c -o src/phraseanet_indexer-callback_record.o `test -f 'src/callback_record.cpp' || echo '$(srcdir)/'`src/callback_record.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-callback_record.Tpo src/$(DEPDIR)/phraseanet_indexer-callback_record.Po
#	source='src/callback_record.cpp' object='src/phraseanet_indexer-callback_record.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-callback_record.o `test -f 'src/callback_record.cpp' || echo '$(srcdir)/'`src/callback_record.cpp

src/phraseanet_indexer-callback_record.obj: src/callback_record.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-callback_record.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-callback_record.Tpo -c -o src/phraseanet_indexer-callback_record.obj `if test -f 'src/callback_record.cpp'; then $(CYGPATH_W) 'src/callback_record.cpp'; else $(CYGPATH_W) '$(srcdir)/src/callback_record.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-callback_record.Tpo src/$(DEPDIR)/phraseanet_indexer-callback_record.Po
#	source='src/callback_record.cpp' object='src/phraseanet_indexer-callback_record.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-callback_record.obj `if test -f 'src/callback_record.cpp'; then $(CYGPATH_W) 'src/callback_record.cpp'; else $(CYGPATH_W) '$(srcdir)/src/callback_record.cpp'; fi`

src/phraseanet_indexer-connbas.o: src/connbas.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-connbas.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-connbas.Tpo -c -o src/phraseanet_indexer-connbas.o `test -f 'src/connbas.cpp' || echo '$(srcdir)/'`src/connbas.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-connbas.Tpo src/$(DEPDIR)/phraseanet_indexer-connbas.Po
#	source='src/connbas.cpp' object='src/phraseanet_indexer-connbas.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-connbas.o `test -f 'src/connbas.cpp' || echo '$(srcdir)/'`src/connbas.cpp

src/phraseanet_indexer-connbas.obj: src/connbas.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-connbas.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-connbas.Tpo -c -o src/phraseanet_indexer-connbas.obj `if test -f 'src/connbas.cpp'; then $(CYGPATH_W) 'src/connbas.cpp'; else $(CYGPATH_W) '$(srcdir)/src/connbas.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-connbas.Tpo src/$(DEPDIR)/phraseanet_indexer-connbas.Po
#	source='src/connbas.cpp' object='src/phraseanet_indexer-connbas.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-connbas.obj `if test -f 'src/connbas.cpp'; then $(CYGPATH_W) 'src/connbas.cpp'; else $(CYGPATH_W) '$(srcdir)/src/connbas.cpp'; fi`

src/phraseanet_indexer-connbas_abox.o: src/connbas_abox.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-connbas_abox.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-connbas_abox.Tpo -c -o src/phraseanet_indexer-connbas_abox.o `test -f 'src/connbas_abox.cpp' || echo '$(srcdir)/'`src/connbas_abox.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-connbas_abox.Tpo src/$(DEPDIR)/phraseanet_indexer-connbas_abox.Po
#	source='src/connbas_abox.cpp' object='src/phraseanet_indexer-connbas_abox.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-connbas_abox.o `test -f 'src/connbas_abox.cpp' || echo '$(srcdir)/'`src/connbas_abox.cpp

src/phraseanet_indexer-connbas_abox.obj: src/connbas_abox.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-connbas_abox.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-connbas_abox.Tpo -c -o src/phraseanet_indexer-connbas_abox.obj `if test -f 'src/connbas_abox.cpp'; then $(CYGPATH_W) 'src/connbas_abox.cpp'; else $(CYGPATH_W) '$(srcdir)/src/connbas_abox.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-connbas_abox.Tpo src/$(DEPDIR)/phraseanet_indexer-connbas_abox.Po
#	source='src/connbas_abox.cpp' object='src/phraseanet_indexer-connbas_abox.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-connbas_abox.obj `if test -f 'src/connbas_abox.cpp'; then $(CYGPATH_W) 'src/connbas_abox.cpp'; else $(CYGPATH_W) '$(srcdir)/src/connbas_abox.cpp'; fi`

src/phraseanet_indexer-connbas_dbox.o: src/connbas_dbox.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-connbas_dbox.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-connbas_dbox.Tpo -c -o src/phraseanet_indexer-connbas_dbox.o `test -f 'src/connbas_dbox.cpp' || echo '$(srcdir)/'`src/connbas_dbox.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-connbas_dbox.Tpo src/$(DEPDIR)/phraseanet_indexer-connbas_dbox.Po
#	source='src/connbas_dbox.cpp' object='src/phraseanet_indexer-connbas_dbox.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-connbas_dbox.o `test -f 'src/connbas_dbox.cpp' || echo '$(srcdir)/'`src/connbas_dbox.cpp

src/phraseanet_indexer-connbas_dbox.obj: src/connbas_dbox.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-connbas_dbox.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-connbas_dbox.Tpo -c -o src/phraseanet_indexer-connbas_dbox.obj `if test -f 'src/connbas_dbox.cpp'; then $(CYGPATH_W) 'src/connbas_dbox.cpp'; else $(CYGPATH_W) '$(srcdir)/src/connbas_dbox.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-connbas_dbox.Tpo src/$(DEPDIR)/phraseanet_indexer-connbas_dbox.Po
#	source='src/connbas_dbox.cpp' object='src/phraseanet_indexer-connbas_dbox.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-connbas_dbox.obj `if test -f 'src/connbas_dbox.cpp'; then $(CYGPATH_W) 'src/connbas_dbox.cpp'; else $(CYGPATH_W) '$(srcdir)/src/connbas_dbox.cpp'; fi`

src/phraseanet_indexer-dom.o: src/dom.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-dom.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-dom.Tpo -c -o src/phraseanet_indexer-dom.o `test -f 'src/dom.cpp' || echo '$(srcdir)/'`src/dom.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-dom.Tpo src/$(DEPDIR)/phraseanet_indexer-dom.Po
#	source='src/dom.cpp' object='src/phraseanet_indexer-dom.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-dom.o `test -f 'src/dom.cpp' || echo '$(srcdir)/'`src/dom.cpp

src/phraseanet_indexer-dom.obj: src/dom.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-dom.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-dom.Tpo -c -o src/phraseanet_indexer-dom.obj `if test -f 'src/dom.cpp'; then $(CYGPATH_W) 'src/dom.cpp'; else $(CYGPATH_W) '$(srcdir)/src/dom.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-dom.Tpo src/$(DEPDIR)/phraseanet_indexer-dom.Po
#	source='src/dom.cpp' object='src/phraseanet_indexer-dom.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-dom.obj `if test -f 'src/dom.cpp'; then $(CYGPATH_W) 'src/dom.cpp'; else $(CYGPATH_W) '$(srcdir)/src/dom.cpp'; fi`

src/phraseanet_indexer-indexer.o: src/indexer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-indexer.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-indexer.Tpo -c -o src/phraseanet_indexer-indexer.o `test -f 'src/indexer.cpp' || echo '$(srcdir)/'`src/indexer.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-indexer.Tpo src/$(DEPDIR)/phraseanet_indexer-indexer.Po
#	source='src/indexer.cpp' object='src/phraseanet_indexer-indexer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-indexer.o `test -f 'src/indexer.cpp' || echo '$(srcdir)/'`src/indexer.cpp

src/phraseanet_indexer-indexer.obj: src/indexer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-indexer.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-indexer.Tpo -c -o src/phraseanet_indexer-indexer.obj `if test -f 'src/indexer.cpp'; then $(CYGPATH_W) 'src/indexer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/indexer.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-indexer.Tpo src/$(DEPDIR)/phraseanet_indexer-indexer.Po
#	source='src/indexer.cpp' object='src/phraseanet_indexer-indexer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-indexer.obj `if test -f 'src/indexer.cpp'; then $(CYGPATH_W) 'src/indexer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/indexer.cpp'; fi`

src/phraseanet_indexer-unicode.o: src/unicode.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-unicode.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-unicode.Tpo -c -o src/phraseanet_indexer-unicode.o `test -f 'src/unicode.cpp' || echo '$(srcdir)/'`src/unicode.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-unicode.Tpo src/$(DEPDIR)/phraseanet_indexer-unicode.Po
#	source='src/unicode.cpp' object='src/phraseanet_indexer-unicode.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-unicode.o `test -f 'src/unicode.cpp' || echo '$(srcdir)/'`src/unicode.cpp

src/phraseanet_indexer-unicode.obj: src/unicode.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-unicode.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-unicode.Tpo -c -o src/phraseanet_indexer-unicode.obj `if test -f 'src/unicode.cpp'; then $(CYGPATH_W) 'src/unicode.cpp'; else $(CYGPATH_W) '$(srcdir)/src/unicode.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-unicode.Tpo src/$(DEPDIR)/phraseanet_indexer-unicode.Po
#	source='src/unicode.cpp' object='src/phraseanet_indexer-unicode.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-unicode.obj `if test -f 'src/unicode.cpp'; then $(CYGPATH_W) 'src/unicode.cpp'; else $(CYGPATH_W) '$(srcdir)/src/unicode.cpp'; fi`

src/phraseanet_indexer-phrasea_clock_t.o: src/phrasea_clock_t.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-phrasea_clock_t.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-phrasea_clock_t.Tpo -c -o src/phraseanet_indexer-phrasea_clock_t.o `test -f 'src/phrasea_clock_t.cpp' || echo '$(srcdir)/'`src/phrasea_clock_t.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-phrasea_clock_t.Tpo src/$(DEPDIR)/phraseanet_indexer-phrasea_clock_t.Po
#	source='src/phrasea_clock_t.cpp' object='src/phraseanet_indexer-phrasea_clock_t.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-phrasea_clock_t.o `test -f 'src/phrasea_clock_t.cpp' || echo '$(srcdir)/'`src/phrasea_clock_t.cpp

src/phraseanet_indexer-phrasea_clock_t.obj: src/phrasea_clock_t.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-phrasea_clock_t.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-phrasea_clock_t.Tpo -c -o src/phraseanet_indexer-phrasea_clock_t.obj `if test -f 'src/phrasea_clock_t.cpp'; then $(CYGPATH_W) 'src/phrasea_clock_t.cpp'; else $(CYGPATH_W) '$(srcdir)/src/phrasea_clock_t.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-phrasea_clock_t.Tpo src/$(DEPDIR)/phraseanet_indexer-phrasea_clock_t.Po
#	source='src/phrasea_clock_t.cpp' object='src/phraseanet_indexer-phrasea_clock_t.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-phrasea_clock_t.obj `if test -f 'src/phrasea_clock_t.cpp'; then $(CYGPATH_W) 'src/phrasea_clock_t.cpp'; else $(CYGPATH_W) '$(srcdir)/src/phrasea_clock_t.cpp'; fi`

src/phraseanet_indexer-sbas.o: src/sbas.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-sbas.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-sbas.Tpo -c -o src/phraseanet_indexer-sbas.o `test -f 'src/sbas.cpp' || echo '$(srcdir)/'`src/sbas.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-sbas.Tpo src/$(DEPDIR)/phraseanet_indexer-sbas.Po
#	source='src/sbas.cpp' object='src/phraseanet_indexer-sbas.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-sbas.o `test -f 'src/sbas.cpp' || echo '$(srcdir)/'`src/sbas.cpp

src/phraseanet_indexer-sbas.obj: src/sbas.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-sbas.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-sbas.Tpo -c -o src/phraseanet_indexer-sbas.obj `if test -f 'src/sbas.cpp'; then $(CYGPATH_W) 'src/sbas.cpp'; else $(CYGPATH_W) '$(srcdir)/src/sbas.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-sbas.Tpo src/$(DEPDIR)/phraseanet_indexer-sbas.Po
#	source='src/sbas.cpp' object='src/phraseanet_indexer-sbas.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-sbas.obj `if test -f 'src/sbas.cpp'; then $(CYGPATH_W) 'src/sbas.cpp'; else $(CYGPATH_W) '$(srcdir)/src/sbas.cpp'; fi`

src/phraseanet_indexer-thesaurus.o: src/thesaurus.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-thesaurus.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-thesaurus.Tpo -c -o src/phraseanet_indexer-thesaurus.o `test -f 'src/thesaurus.cpp' || echo '$(srcdir)/'`src/thesaurus.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-thesaurus.Tpo src/$(DEPDIR)/phraseanet_indexer-thesaurus.Po
#	source='src/thesaurus.cpp' object='src/phraseanet_indexer-thesaurus.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-thesaurus.o `test -f 'src/thesaurus.cpp' || echo '$(srcdir)/'`src/thesaurus.cpp

src/phraseanet_indexer-thesaurus.obj: src/thesaurus.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-thesaurus.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-thesaurus.Tpo -c -o src/phraseanet_indexer-thesaurus.obj `if test -f 'src/thesaurus.cpp'; then $(CYGPATH_W) 'src/thesaurus.cpp'; else $(CYGPATH_W) '$(srcdir)/src/thesaurus.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-thesaurus.Tpo src/$(DEPDIR)/phraseanet_indexer-thesaurus.Po
#	source='src/thesaurus.cpp' object='src/phraseanet_indexer-thesaurus.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-thesaurus.obj `if test -f 'src/thesaurus.cpp'; then $(CYGPATH_W) 'src/thesaurus.cpp'; else $(CYGPATH_W) '$(srcdir)/src/thesaurus.cpp'; fi`

src/phraseanet_indexer-trace_memory.o: src/trace_memory.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-trace_memory.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-trace_memory.Tpo -c -o src/phraseanet_indexer-trace_memory.o `test -f 'src/trace_memory.cpp' || echo '$(srcdir)/'`src/trace_memory.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-trace_memory.Tpo src/$(DEPDIR)/phraseanet_indexer-trace_memory.Po
#	source='src/trace_memory.cpp' object='src/phraseanet_indexer-trace_memory.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-trace_memory.o `test -f 'src/trace_memory.cpp' || echo '$(srcdir)/'`src/trace_memory.cpp

src/phraseanet_indexer-trace_memory.obj: src/trace_memory.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-trace_memory.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-trace_memory.Tpo -c -o src/phraseanet_indexer-trace_memory.obj `if test -f 'src/trace_memory.cpp'; then $(CYGPATH_W) 'src/trace_memory.cpp'; else $(CYGPATH_W) '$(srcdir)/src/trace_memory.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-trace_memory.Tpo src/$(DEPDIR)/phraseanet_indexer-trace_memory.Po
#	source='src/trace_memory.cpp' object='src/phraseanet_indexer-trace_memory.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-trace_memory.obj `if test -f 'src/trace_memory.cpp'; then $(CYGPATH_W) 'src/trace_memory.cpp'; else $(CYGPATH_W) '$(srcdir)/src/trace_memory.cpp'; fi`

src/phraseanet_indexer-sockets.o: src/sockets.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-sockets.o -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-sockets.Tpo -c -o src/phraseanet_indexer-sockets.o `test -f 'src/sockets.cpp' || echo '$(srcdir)/'`src/sockets.cpp
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-sockets.Tpo src/$(DEPDIR)/phraseanet_indexer-sockets.Po
#	source='src/sockets.cpp' object='src/phraseanet_indexer-sockets.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-sockets.o `test -f 'src/sockets.cpp' || echo '$(srcdir)/'`src/sockets.cpp

src/phraseanet_indexer-sockets.obj: src/sockets.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT src/phraseanet_indexer-sockets.obj -MD -MP -MF src/$(DEPDIR)/phraseanet_indexer-sockets.Tpo -c -o src/phraseanet_indexer-sockets.obj `if test -f 'src/sockets.cpp'; then $(CYGPATH_W) 'src/sockets.cpp'; else $(CYGPATH_W) '$(srcdir)/src/sockets.cpp'; fi`
	$(am__mv) src/$(DEPDIR)/phraseanet_indexer-sockets.Tpo src/$(DEPDIR)/phraseanet_indexer-sockets.Po
#	source='src/sockets.cpp' object='src/phraseanet_indexer-sockets.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o src/phraseanet_indexer-sockets.obj `if test -f 'src/sockets.cpp'; then $(CYGPATH_W) 'src/sockets.cpp'; else $(CYGPATH_W) '$(srcdir)/src/sockets.cpp'; fi`

xNIX/phraseanet_indexer-syslog_xnix.o: xNIX/syslog_xnix.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT xNIX/phraseanet_indexer-syslog_xnix.o -MD -MP -MF xNIX/$(DEPDIR)/phraseanet_indexer-syslog_xnix.Tpo -c -o xNIX/phraseanet_indexer-syslog_xnix.o `test -f 'xNIX/syslog_xnix.cpp' || echo '$(srcdir)/'`xNIX/syslog_xnix.cpp
	$(am__mv) xNIX/$(DEPDIR)/phraseanet_indexer-syslog_xnix.Tpo xNIX/$(DEPDIR)/phraseanet_indexer-syslog_xnix.Po
#	source='xNIX/syslog_xnix.cpp' object='xNIX/phraseanet_indexer-syslog_xnix.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o xNIX/phraseanet_indexer-syslog_xnix.o `test -f 'xNIX/syslog_xnix.cpp' || echo '$(srcdir)/'`xNIX/syslog_xnix.cpp

xNIX/phraseanet_indexer-syslog_xnix.obj: xNIX/syslog_xnix.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT xNIX/phraseanet_indexer-syslog_xnix.obj -MD -MP -MF xNIX/$(DEPDIR)/phraseanet_indexer-syslog_xnix.Tpo -c -o xNIX/phraseanet_indexer-syslog_xnix.obj `if test -f 'xNIX/syslog_xnix.cpp'; then $(CYGPATH_W) 'xNIX/syslog_xnix.cpp'; else $(CYGPATH_W) '$(srcdir)/xNIX/syslog_xnix.cpp'; fi`
	$(am__mv) xNIX/$(DEPDIR)/phraseanet_indexer-syslog_xnix.Tpo xNIX/$(DEPDIR)/phraseanet_indexer-syslog_xnix.Po
#	source='xNIX/syslog_xnix.cpp' object='xNIX/phraseanet_indexer-syslog_xnix.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(phraseanet_indexer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o xNIX/phraseanet_indexer-syslog_xnix.obj `if test -f 'xNIX/syslog_xnix.cpp'; then $(CYGPATH_W) 'xNIX/syslog_xnix.cpp'; else $(CYGPATH_W) '$(srcdir)/xNIX/syslog_xnix.cpp'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

$(RECURSIVE_CLEAN_TARGETS):
	@fail= failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(MKDIR_P) "$(distdir)/$$subdir" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS)
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f xNIX/$(DEPDIR)/$(am__dirstamp)
	-rm -f xNIX/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR) xNIX/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am:

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR) xNIX/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) ctags-recursive \
	install-am install-strip tags-recursive

.PHONY: $(RECURSIVE_CLEAN_TARGETS) $(RECURSIVE_TARGETS) CTAGS GTAGS \
	all all-am am--refresh check check-am clean clean-binPROGRAMS \
	clean-generic clean-libtool ctags ctags-recursive dist \
	dist-all dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags \
	distcleancheck distdir distuninstallcheck dvi dvi-am html \
	html-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs installdirs-am \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags tags-recursive uninstall uninstall-am \
	uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
